Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'controls/example.rb'

Lint/ImplicitStringConcatenation:
  Exclude:
    - 'libraries/ec2_instance.rb'

# Explicit is better than implicit
Style/AccessorMethodName:
  Exclude:
    - 'libraries/ec2_instance.rb'

# Explicit is better than implicit
Style/RedundantReturn:
  Exclude:
    - 'libraries/ec2_instance.rb'

Style/RegexpLiteral:
  Exclude:
    - 'libraries/ec2_instance.rb'

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 40
